# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sraeisid/Merged_FaNDOM/FaNDOM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sraeisid/Merged_FaNDOM/FaNDOM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sraeisid/Merged_FaNDOM/FaNDOM/CMakeFiles /home/sraeisid/Merged_FaNDOM/FaNDOM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sraeisid/Merged_FaNDOM/FaNDOM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FaNDOM

# Build rule for target.
FaNDOM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FaNDOM
.PHONY : FaNDOM

# fast build rule for target.
FaNDOM/fast:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/build
.PHONY : FaNDOM/fast

OMFilter.o: OMFilter.cpp.o

.PHONY : OMFilter.o

# target to build an object file
OMFilter.cpp.o:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/OMFilter.cpp.o
.PHONY : OMFilter.cpp.o

OMFilter.i: OMFilter.cpp.i

.PHONY : OMFilter.i

# target to preprocess a source file
OMFilter.cpp.i:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/OMFilter.cpp.i
.PHONY : OMFilter.cpp.i

OMFilter.s: OMFilter.cpp.s

.PHONY : OMFilter.s

# target to generate assembly for a file
OMFilter.cpp.s:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/OMFilter.cpp.s
.PHONY : OMFilter.cpp.s

OMHelper.o: OMHelper.cpp.o

.PHONY : OMHelper.o

# target to build an object file
OMHelper.cpp.o:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/OMHelper.cpp.o
.PHONY : OMHelper.cpp.o

OMHelper.i: OMHelper.cpp.i

.PHONY : OMHelper.i

# target to preprocess a source file
OMHelper.cpp.i:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/OMHelper.cpp.i
.PHONY : OMHelper.cpp.i

OMHelper.s: OMHelper.cpp.s

.PHONY : OMHelper.s

# target to generate assembly for a file
OMHelper.cpp.s:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/OMHelper.cpp.s
.PHONY : OMHelper.cpp.s

OMIO.o: OMIO.cpp.o

.PHONY : OMIO.o

# target to build an object file
OMIO.cpp.o:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/OMIO.cpp.o
.PHONY : OMIO.cpp.o

OMIO.i: OMIO.cpp.i

.PHONY : OMIO.i

# target to preprocess a source file
OMIO.cpp.i:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/OMIO.cpp.i
.PHONY : OMIO.cpp.i

OMIO.s: OMIO.cpp.s

.PHONY : OMIO.s

# target to generate assembly for a file
OMIO.cpp.s:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/OMIO.cpp.s
.PHONY : OMIO.cpp.s

SeedGraph.o: SeedGraph.cpp.o

.PHONY : SeedGraph.o

# target to build an object file
SeedGraph.cpp.o:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/SeedGraph.cpp.o
.PHONY : SeedGraph.cpp.o

SeedGraph.i: SeedGraph.cpp.i

.PHONY : SeedGraph.i

# target to preprocess a source file
SeedGraph.cpp.i:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/SeedGraph.cpp.i
.PHONY : SeedGraph.cpp.i

SeedGraph.s: SeedGraph.cpp.s

.PHONY : SeedGraph.s

# target to generate assembly for a file
SeedGraph.cpp.s:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/SeedGraph.cpp.s
.PHONY : SeedGraph.cpp.s

fandomAligner.o: fandomAligner.cpp.o

.PHONY : fandomAligner.o

# target to build an object file
fandomAligner.cpp.o:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/fandomAligner.cpp.o
.PHONY : fandomAligner.cpp.o

fandomAligner.i: fandomAligner.cpp.i

.PHONY : fandomAligner.i

# target to preprocess a source file
fandomAligner.cpp.i:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/fandomAligner.cpp.i
.PHONY : fandomAligner.cpp.i

fandomAligner.s: fandomAligner.cpp.s

.PHONY : fandomAligner.s

# target to generate assembly for a file
fandomAligner.cpp.s:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/fandomAligner.cpp.s
.PHONY : fandomAligner.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/FaNDOM.dir/build.make CMakeFiles/FaNDOM.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... FaNDOM"
	@echo "... OMFilter.o"
	@echo "... OMFilter.i"
	@echo "... OMFilter.s"
	@echo "... OMHelper.o"
	@echo "... OMHelper.i"
	@echo "... OMHelper.s"
	@echo "... OMIO.o"
	@echo "... OMIO.i"
	@echo "... OMIO.s"
	@echo "... SeedGraph.o"
	@echo "... SeedGraph.i"
	@echo "... SeedGraph.s"
	@echo "... fandomAligner.o"
	@echo "... fandomAligner.i"
	@echo "... fandomAligner.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

